### ISSUE TITLE
Please add more documentation

### ISSUE THREAD

**Issue by maxigimenez** [ex-machine/ng-debottle#1]
Add a README.md with some documentation of how to use it

**Comment by bisubus** [comment]
@maxigimenez 

 `$throttle` and `$debounce` services come with arguments similar to the ones in `$timeout`,

```
angular.module('app', ['ngDebottle']).run(function ($rootScope, $throttle, $debounce) {
    function fn() { ... }
    var throttledFn = $throttle(fn, 100);
    var debouncedFn = $debounce(fn, 100);

    $rootScope.$on('...', throttledFn);
    $rootScope.$on('...', debouncedFn );
    // instead of
    // $rootScope.$on('...', fn);
});
```

throttledFn and debouncedFn get `$delay` property to control the delay dynamically, `$timeout` property that reflects current throttle/debounce cycle, and `$cancel` method to cancel the cycle.

I will update the repo with full-fledged readme as I will get some time.

**Comment by maxigimenez** [comment]
Awesome, thanks!
